### PR TITLE
percentiles notebook

### PR DESCRIPTION
**Pull request by AliciaTak**

### CODE REVIEW

**Review by DamienIrving — CHANGES_REQUESTED** [review]
This looks really great, @AliciaTak.

One quick comment - the colorbar on the precipitation plots probably needs tweaking (the `np.arange(-200, 200.1, 50)` levels were used for mean annual rainfall - the values here are going to be much smaller because we're just looking at extreme daily totals).

**Comment by AliciaTak** [comment]
> This looks really great, @AliciaTak.
> 
> One quick comment - the colorbar on the precipitation plots probably needs tweaking (the `np.arange(-200, 200.1, 50)` levels were used for mean annual rainfall - the values here are going to be much smaller because we're just looking at extreme daily totals).

No worries, I'll fix it and create another pull request. Also, I am almost done with interannual and multi-year variability biases.

**Comment by AliciaTak** [comment]
Could you hang on with accepting the variability notebook, please? I need to change the unit for pr from mm/day to mm/year. I'll update the pull request in a couple of minutes again.

**Comment by AliciaTak** [comment]
> Could you hang on with accepting the variability notebook, please? I need to change the unit for pr from mm/day to mm/year. I'll update the pull request in a couple of minutes again.

Ok, done!

**Pull request merged**
