### PR TITLE
rearranged notebooks

### PR DESCRIPTION
**Pull request by AliciaTak**
@DamienIrving I didn't bother implementing the modification for the performance, as you mentioned that the improvements are modest.

### CODE REVIEW

**Review by DamienIrving — COMMENTED** [review]
Just one comment on this one @AliciaTak - it looks like the results are exactly the same for the 99th, 99.5th and 99.9th percentile in the precipitation notebook? (The temperature notebooks are fine.) I had a quick look but couldn't pinpoint the problem.

**Comment by AliciaTak** [comment]
> Just one comment on this one @AliciaTak - it looks like the results are exactly the same for the 99th, 99.5th and 99.9th percentile in the precipitation notebook? (The temperature notebooks are fine.) I had a quick look but couldn't pinpoint the problem.

@DamienIrving I noticed this too and checked the code, but I couldn't detect anything (it's exactly the same code as for temperature; only the variable name is changing). Could it be that higher rainfall percentiles are the same?

**Comment by AliciaTak** [comment]
> > Just one comment on this one @AliciaTak - it looks like the results are exactly the same for the 99th, 99.5th and 99.9th percentile in the precipitation notebook? (The temperature notebooks are fine.) I had a quick look but couldn't pinpoint the problem.
> 
> @DamienIrving I noticed this too and checked the code, but I couldn't detect anything (it's exactly the same code as for temperature; only the variable name is changing). Could it be that higher rainfall percentiles are the same?

@DamienIrving I noticed that I need to correct the code for tasmax, as I am masking out values for tasmax as for pr.

**Comment by DamienIrving** [comment]
It might be that the precip values are all the same at high percentiles... we can merge this for now after you've re-run tasmax and look into the high precip percentiles later.

**Comment by AliciaTak** [comment]
> It might be that the precip values are all the same at high percentiles... we can merge this for now after you've re-run tasmax and look into the high precip percentiles later.

@DamienIrving I just did the test; they shouldn't be the same. I'll try to figure out what's going wrong.

**Comment by AliciaTak** [comment]
> > It might be that the precip values are all the same at high percentiles... we can merge this for now after you've re-run tasmax and look into the high precip percentiles later.
> 
> @DamienIrving I just did the test; they shouldn't be the same. I'll try to figure out what's going wrong.

@DamienIrving I think I found the error; it was a loop that always calculated the bias for the 99.9th perc.:
I had 
```python
 if var == 'pr' or var == 'tasmax' and percentile == '99th':
        bias = perc1_model - perc1_obs 
```
instead of 
```python
 if (var == 'pr' and percentile == '99th') or (var == 'tasmax' and percentile == '99th'):
        bias = perc1_model - perc1_obs 
```

**Pull request merged**
