### PR TITLE
initial commit of the drought notebook

### PR DESCRIPTION
**Pull request by AliciaTak**
@DamienIrving I need your opinion on this; does it make sense if I have negative % bias as red and positive % bias as blue as they refer to drought (i.e., red: less precipitation, blue: more precipitation)? Could you also have a look at the calculation of the percentage deviation, would you do it in the same way? Thanks!

### CODE REVIEW

**Comment by DamienIrving** [comment]
To avoid confusion with the red/blue colors, you could use 'BrBG' instead of 'RdBu'? That would make it brown for increasing drought risk and green for decreased drought risk.

**Review by DamienIrving — COMMENTED** [review]
If I'm interpreting correctly, positive values on these plots means there is a higher drought risk in the models than in obs? If that's the case, you might actually want to use "BrBG_r" so that positive values are a drought color (brown). In other words, brown means the models simulate too much drought and green means not enough drought. Does that make sense? (Sorry, I should have suggested "BrBG_r" in the first place.)

**Comment by AliciaTak** [comment]
> If I'm interpreting correctly, positive values on these plots means there is a higher drought risk in the models than in obs? If that's the case, you might actually want to use "BrBG_r" so that positive values are a drought color (brown). In other words, brown means the models simulate too much drought and green means not enough drought. Does that make sense? (Sorry, I should have suggested "BrBG_r" in the first place.)

@DamienIrving No, positive values mean that there is more precipitation in the model than in the obs, and hence less drought risk. Negative values mean that there is less precipitation and more drought risk. If that's too confusing, maybe the percentage drought risk needs to be calculated in a different way?

**Comment by DamienIrving** [comment]
Is that a commonly used drought index? Rather than drought risk (which brings to mind the odds of getting a drought in any given year) the difference between the very driest rainfall value and the mean rainfall value feels to me more like a very simple index of the maximum drought intensity.

**Comment by AliciaTak** [comment]
> Rather than drought risk (which brings to mind the odds of getting a drought in any given year)

@DamienIrving This is the description of the calculation method; it's the multiannual drought risk:
"As a proxy for drought risks, we calculated the minimum of precipitation over the evaluation period, as a %-deviation of the climatological mean. Equally, we calculated the minimum over the evaluation period from 2- to 5-year averaged values (using 2- to 5-year moving averages) as a %-deviation from the long-term mean."
Vanessa Round is dealing with drought a lot, I could ask her if she can recommend another metric.

**Comment by DamienIrving** [comment]
The Vogel paper tends to refer to it as a measure of drought "magnitude" as opposed to "risk" - I reckon if you change the wording in your notebook to "drought magnitude" that should clear up any confusion :smile:

> To assess the magnitude of drought at multiple time scales (annual to 5-year multiannual drought), we calculated the minimum of 1- to 5-year precipitation, soil moisture and runoff averaged values and compared it against the long-term average. In other words, we assessed, “How dry was the driest 1- to 5-year period relative to average precipitation, soil moisture and runoff – in the observations and downscaled / bias corrected data?”

**Comment by AliciaTak** [comment]
> The Vogel paper tends to refer to it as a measure of drought "magnitude" as opposed to "risk" - I reckon if you change the wording in your notebook to "drought magnitude" that should clear up any confusion 😄
> 
> > To assess the magnitude of drought at multiple time scales (annual to 5-year multiannual drought), we calculated the minimum of 1- to 5-year precipitation, soil moisture and runoff averaged values and compared it against the long-term average. In other words, we assessed, “How dry was the driest 1- to 5-year period relative to average precipitation, soil moisture and runoff – in the observations and downscaled / bias corrected data?”

OK, I understand, will change the wording.

**Pull request merged**
