### PR TITLE
climatology notebook

### PR DESCRIPTION
**Pull request by AliciaTak**

### CODE REVIEW

**Review by DamienIrving — CHANGES_REQUESTED** [review]
Looks good, Alicia.

Just one comment - I think the following works fine for temperature (i.e. it takes the mean of all the days that fall within a given month)... 
```python
climatology = da.groupby('time.month').mean(dim='time')
```

... but I don't think this is correct for rainfall (it will give the 20-year rainfall total for each month - that's why the values are so large in the rainfall plots):
```python
climatology = da.groupby('time.month').sum(dim='time')
```
Instead, for rainfall I think you want to calculate the average monthly rainfall total by running:
```python
da_monthly = da.resample(time='1M').sum()
climatology = da_monthly.groupby('time.month').mean('time')
```

**Comment by AliciaTak** [comment]
> Looks good, Alicia.
> 
> Just one comment - I think the following works fine for temperature (i.e. it takes the mean of all the days that fall within a given month)...
> 
> ```python
> climatology = da.groupby('time.month').mean(dim='time')
> ```
> 
> ... but I don't think this is correct for rainfall (it will give the 20-year rainfall total for each month - that's why the values are so large in the rainfall plots):
> 
> ```python
> climatology = da.groupby('time.month').sum(dim='time')
> ```
> 
> Instead, for rainfall I think you want to calculate the average monthly rainfall total by running:
> 
> ```python
> da_monthly = da.resample(time='1M').sum()
> climatology = da_monthly.groupby('time.month').mean('time')
> ```

@DamienIrving Thanks for picking this up! I'll update the notebook.

**Comment by AliciaTak** [comment]
@DamienIrving I changed the calculation to the suggested one, but the spatial climatology plots for precip are not masked for the ocean portion. I didn't do any additional masking, because I thought it might not be important for now. But if you think it should be done now, then let me know, please.

**Review by DamienIrving — APPROVED** [review]
I wouldn't worry about the ocean masking for now.

It looks like `utils.get_npcp_data` returns clipped data with NaNs over the ocean, but the operations that get performed on the data (sum, mean, etc) change the NaNs to zeros, even if the `skipna=True` argument is used.

To fix it we'd have to clip the data right before we plot it, e.g.
```python
bias = utils.clip_data(bias, utils.get_aus_chape())
```
But we can just do that next time we have to re-run the notebook to add an extra model or bias correction method or whatever.

**Pull request merged**
